title       = "gitee"
baseURL     = "https://gitee-cli.tamnd.com/"
description = "Browse Gitee repositories and users"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/gitee-cli"
